import { access, mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const widgetsDir = path.join(root, "src", "widgets");
const generatedDir = path.join(root, "src", "generated");

async function exists(file: string) {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  const entries = await readdir(widgetsDir, { withFileTypes: true });
  const widgets = entries
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("_"))
    .map((entry) => entry.name)
    .sort();

  if (widgets.length === 0) throw new Error("No widgets found in src/widgets");

  for (const widget of widgets) {
    for (const file of ["definition.ts", "component.tsx"]) {
      const target = path.join(widgetsDir, widget, file);
      if (!(await exists(target))) throw new Error(`Widget ${widget} is missing ${file}`);
    }
  }

  const serverImports = widgets
    .map((name, index) => `import { definition as widget${index} } from "@/widgets/${name}/definition";`)
    .join("\n");
  const clientImports = widgets
    .map((name, index) => `import Widget${index} from "@/widgets/${name}/component";`)
    .join("\n");

  const server = `// Generated by scripts/generate-widget-registry.ts — do not edit.\n${serverImports}\n\nexport const generatedWidgetDefinitions = [${widgets.map((_, index) => `widget${index}`).join(", ")}] as const;\n`;
  const client = `// Generated by scripts/generate-widget-registry.ts — do not edit.\n\"use client\";\n\nimport type { ComponentType } from \"react\";\nimport type { WidgetViewProps } from \"@/widget-engine/contracts\";\n${clientImports}\n\nexport const generatedWidgetComponents: Record<string, ComponentType<WidgetViewProps>> = {\n${widgets.map((name, index) => `  ${JSON.stringify(name)}: Widget${index},`).join("\n")}\n};\n`;

  await mkdir(generatedDir, { recursive: true });
  await Promise.all([
    writeFile(path.join(generatedDir, "widget-registry.server.ts"), server, "utf8"),
    writeFile(path.join(generatedDir, "widget-registry.client.tsx"), client, "utf8"),
  ]);
  console.log(`Generated widget registry with ${widgets.length} widgets: ${widgets.join(", ")}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
